name: test

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build bytecode
        run: |
          make build
        id: build

      - name: Run Forge build
        # this is mostly here so that warnings from building forge-std
        # do not appear in the test output
        run: |
          forge --version
          forge build --sizes

      - name: Run contract tests
        run: |
          make test
        id: test
